sudo: false

language: scala

jdk: openjdk8

scala:
  - 2.12.12

env:
  global:
    BUILD_NUMBER=$TRAVIS_BUILD_NUMBER
  # This splits the build into two parts
  matrix:
    - COMMAND="compile;scalafix;package;publish"
    #- TEST_COMMAND="scripted merging/* caching/*"
script:
  - sbt -Dfile.encoding=UTF8 -J-XX:ReservedCodeCacheSize=256M "$COMMAND"

before_cache:
  - rm -fv $HOME/.ivy2/.sbt.ivy.lock
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete

cache:
  directories:
    - $HOME/.cache/coursier
    - $HOME/.ivy2/cache
    - $HOME/.ivy2/local
    - $HOME/.sbt